import React, { useEffect, useState } from 'react';
import SectionContainer from './ui/SectionContainer';
import { fetchTechTrends } from '../services/gemini';
import { Sparkles, ExternalLink, RefreshCw } from 'lucide-react';
import { motion } from 'framer-motion';

const TechInsights: React.FC = () => {
  const [content, setContent] = useState<string>('');
  const [sources, setSources] = useState<{ title: string; url: string }[]>([]);
  const [loading, setLoading] = useState(true);

  const getInsights = async () => {
    setLoading(true);
    const data = await fetchTechTrends();
    setContent(data.content);
    setSources(data.sources);
    setLoading(false);
  };

  useEffect(() => {
    getInsights();
  }, []);

  return (
    <div className="bg-surface dark:bg-[#141218]">
      <SectionContainer id="insights" className="relative">
        <div className="flex flex-col items-center mb-12 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-tertiary-container text-tertiary-onContainer mb-4">
            <Sparkles size={16} />
            <span className="text-sm font-bold tracking-wide uppercase">AI-Powered Insights</span>
          </div>
          <h2 className="text-4xl md:text-5xl font-display font-bold text-slate-900 dark:text-white mb-4">
            Web Trends
          </h2>
          <p className="text-lg text-slate-600 dark:text-slate-400 max-w-2xl">
            Real-time insights generated by Gemini 2.0 Flash, grounded with Google Search.
          </p>
        </div>

        <motion.div 
          className="relative overflow-hidden bg-surface-container dark:bg-[#2B2930] rounded-3xl p-8 md:p-12 shadow-sm"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
            {loading ? (
              <div className="flex flex-col items-center justify-center py-12 space-y-4">
                <RefreshCw className="animate-spin text-primary" size={32} />
                <p className="text-slate-500 font-medium">Analyzing the web...</p>
              </div>
            ) : (
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
                <div className="lg:col-span-2">
                  {/* Using whitespace-pre-wrap to handle paragraphs from the API without a markdown library */}
                  <div className="whitespace-pre-wrap text-lg leading-relaxed text-slate-600 dark:text-slate-300 font-sans">
                    {content}
                  </div>
                </div>
                
                <div className="lg:col-span-1 border-t lg:border-t-0 lg:border-l border-slate-200 dark:border-slate-700 pt-8 lg:pt-0 lg:pl-8">
                  <h3 className="text-sm font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-6">
                    Sources Used
                  </h3>
                  <div className="flex flex-col gap-3">
                    {sources.length > 0 ? (
                      sources.map((source, idx) => (
                        <a 
                          key={idx}
                          href={source.url}
                          target="_blank"
                          rel="noreferrer"
                          className="group flex items-center justify-between p-4 rounded-2xl bg-white dark:bg-[#141218] hover:bg-primary-container dark:hover:bg-primary-container transition-colors"
                        >
                          <span className="text-sm font-medium text-slate-700 dark:text-slate-200 group-hover:text-primary-onContainer truncate mr-4">
                            {source.title}
                          </span>
                          <ExternalLink size={16} className="text-slate-400 group-hover:text-primary-onContainer flex-shrink-0" />
                        </a>
                      ))
                    ) : (
                      <p className="text-sm text-slate-500 italic">No specific web sources cited.</p>
                    )}
                  </div>
                  
                  <button 
                    onClick={getInsights}
                    className="mt-8 flex items-center justify-center gap-2 w-full py-3 rounded-full border border-outline/20 text-sm font-medium hover:bg-surface-dim dark:hover:bg-slate-800 transition-colors"
                  >
                    <RefreshCw size={16} />
                    Refresh Data
                  </button>
                </div>
              </div>
            )}
        </motion.div>
      </SectionContainer>
    </div>
  );
};

export default TechInsights;